**Depends on conda environment: Mito_Assemble (see .env/Mito_Assemble.yml)**

# 1

check the mitochondrial:

In [1]:
from pyfaidx import Fasta

Acer_fa = Fasta("./ref/GCF_029169275.1_AcerK_1.0_genomic.fna")

In [2]:
for name in Acer_fa.keys():
    print(name)

NC_083852.1
NC_083853.1
NC_083854.1
NC_083855.1
NC_083856.1
NC_083857.1
NC_083858.1
NC_083859.1
NC_083860.1
NC_083861.1
NC_083862.1
NC_083863.1
NC_083864.1
NC_083865.1
NC_083866.1
NC_083867.1
NW_026893558.1
NW_026893559.1
NW_026893560.1
NW_026893561.1
NC_014295.1

In [4]:
for name in Acer_fa.keys():
    print(f"{name}: {len(Acer_fa[name])}")

NC_083852.1: 27131825
NC_083853.1: 15875455
NC_083854.1: 13386827
NC_083855.1: 13159592
NC_083856.1: 13471485
NC_083857.1: 17285085
NC_083858.1: 13645534
NC_083859.1: 12170773
NC_083860.1: 11954044
NC_083861.1: 12434583
NC_083862.1: 15832348
NC_083863.1: 11302906
NC_083864.1: 11000381
NC_083865.1: 11731789
NC_083866.1: 9491825
NC_083867.1: 7109830
NW_026893558.1: 5207728
NW_026893559.1: 250740
NW_026893560.1: 93405
NW_026893561.1: 504434
NC_014295.1: 15895

## Search: https://www.ncbi.nlm.nih.gov/nuccore/NC_014295.1/ , indeed a chromosome

# 2

Examine the CDS and exon start site:

In [3]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./metadata/Acer_txinfo.tsv"

Traceback (most recent call last):
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/bin/gppy", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 735, in main
    tx_info(args.gtf, args.force_end_check)
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 548, in tx_info
    meta = tx_meta[tx_id]
           ~~~~~~~^^^^^^^
KeyError: ''

CalledProcessError: Command 'b'\ngppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./metadata/Acer_txinfo.tsv"\n'' returned non-zero exit status 1.

↑ The previous step failed; a suspected partial line contained the following: `transcripr_id ""`

remove `transcripr_id ""`:

In [40]:
%%bash

sed 's/transcript_id ""; //' "./ref/GCF_029169275.1_AcerK_1.0_genomic.gtf" > "./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf"

Try regenerating Acer_txinfo.tsv

In [3]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf" > "./metadata/Acer_txinfo.tsv"

In [1]:
import pandas as pd

In [4]:
Acer_info = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")
Acer_info

/tmp/ipykernel_76250/2624168542.py:1: DtypeWarning: Columns (0: codons, 1: locus_tag) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_info = pd.read_csv("./metadata/Acer_txinfo.tsv", sep="\t")

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,anticodon,...,gbkey,gene,inference,locus_tag,model_evidence,note,partial,product,protein_id,transcript_biotype
0,XM_017048878.3,LOC107992807,NC_083852.1,-,6,713,312,197,204,NaN,...,mRNA,LOC107992807,NaN,NaN,Supporting evidence includes similarity to: 13...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904367.1,mRNA
1,XM_017048879.3,LOC107992807,NC_083852.1,-,5,1167,312,651,204,NaN,...,mRNA,LOC107992807,NaN,NaN,Supporting evidence includes similarity to: 14...,NaN,NaN,"ubiquitin-related modifier 1, transcript varia...",XP_016904368.1,mRNA
2,XM_062082541.1,LOC107992805,NC_083852.1,+,6,4095,3759,155,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 2 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938525.1,mRNA
3,XM_062082566.1,LOC107992805,NC_083852.1,+,7,4344,3717,446,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938550.1,mRNA
4,XM_062082576.1,LOC107992805,NC_083852.1,+,7,4339,3675,483,181,NaN,...,mRNA,LOC107992805,NaN,NaN,Supporting evidence includes similarity to: 1 ...,NaN,NaN,MATH and LRR domain-containing protein PFE0570...,XP_061938560.1,mRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35198,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,...,mRNA,ND1,NaN,KEH14_p01,NaN,NaN,NaN,NaN,YP_003735181.1,mRNA
35199,unassigned_transcript_260,KEH14_t21,NC_014295.1,-,1,69,0,0,0,NaN,...,tRNA,NaN,NaN,KEH14_t21,NaN,NaN,NaN,tRNA-Leu,NaN,tRNA
35200,unassigned_transcript_261,KEH14_r02,NC_014295.1,-,1,1328,0,0,0,NaN,...,rRNA,NaN,NaN,KEH14_r02,NaN,16S ribosomal RNA,NaN,l-rRNA,NaN,rRNA
35201,unassigned_transcript_262,KEH14_t22,NC_014295.1,-,1,67,0,0,0,NaN,...,tRNA,NaN,NaN,KEH14_t22,NaN,NaN,NaN,tRNA-Val,NaN,tRNA
35202,unassigned_transcript_263,KEH14_r01,NC_014295.1,-,1,786,0,0,0,NaN,...,rRNA,NaN,NaN,KEH14_r01,NaN,12S ribosomal RNA,NaN,s-rRNA,NaN,rRNA

In [5]:
Acer_info.columns

Index(['tx_name', 'gene_id', 'chrom', 'strand', 'nexon', 'tx_len', 'cds_len',
       'utr5_len', 'utr3_len', 'anticodon', 'codons', 'db_xref', 'deleted',
       'exception', 'experiment', 'gbkey', 'gene', 'inference', 'locus_tag',
       'model_evidence', 'note', 'partial', 'product', 'protein_id',
       'transcript_biotype'],
      dtype='str')

In [6]:
"gene_biotype" in Acer_info.columns

False

"gene_biotype" not in GTF ?!

In [7]:
Acer_info["transcript_biotype"].unique() # no "protein_coding" in transcript_biotype

<ArrowStringArray>
['mRNA', 'transcript', 'lnc_RNA', 'tRNA', 'snoRNA', 'snRNA', 'rRNA', 'ncRNA']
Length: 8, dtype: str

After verification, I found that the GTF did indeed have a gene_biotype column, but it only appeared in the first row of all rows corresponding to each gene_id:

![Acer](../.image/Pasted%20image%2020260503151005.png)

For comparison, A. mellifera's reference GTF:

![Amel](../.image/Pasted%20image%2020260503151300.png)

To ensure the generality of the process (i.e., [2_make-ref.sh](../2_make-ref.sh) filters for `gene_biotype` rather than `transcript_biotype`), I need to fill in the missing `gene_biotype` values ​​in each line of the current GTF file.

In [8]:
import pyranges as pr
import pandas as pd
from gtfparse import read_gtf

In [9]:
Acer_df = read_gtf("./ref/GCF_029169275.1_AcerK_1.0_genomic_corrected.gtf") # 直接用pyranges读取会出错, 原因未知
Acer_df

INFO:root:Extracted GTF attributes: ['gene_id', 'db_xref', 'description', 'gbkey', 'gene', 'gene_biotype', 'transcript_id', 'experiment', 'model_evidence', 'product', 'transcript_biotype', 'exon_number', 'protein_id', 'part', 'anticodon', 'inference', 'note', 'exception', 'pseudo', 'transl_except', 'gene_synonym', 'partial', 'deleted', 'substituted', 'locus_tag', 'codons', 'transl_table']

shape: (725_105, 35)
┌─────────────┬────────┬────────────┬───────┬───┬─────────────┬───────────┬────────┬──────────────┐
│ seqname     ┆ source ┆ feature    ┆ start ┆ … ┆ substituted ┆ locus_tag ┆ codons ┆ transl_table │
│ ---         ┆ ---    ┆ ---        ┆ ---   ┆   ┆ ---         ┆ ---       ┆ ---    ┆ ---          │
│ cat         ┆ cat    ┆ cat        ┆ i64   ┆   ┆ str         ┆ str       ┆ str    ┆ str          │
╞═════════════╪════════╪════════════╪═══════╪═══╪═════════════╪═══════════╪════════╪══════════════╡
│ NC_083852.1 ┆ Gnomon ┆ gene       ┆ 17569 ┆ … ┆             ┆           ┆        ┆              │
│ NC_083852.1 ┆ Gnomon ┆ transcript ┆ 17569 ┆ … ┆             ┆           ┆        ┆              │
│ NC_083852.1 ┆ Gnomon ┆ exon       ┆ 20093 ┆ … ┆             ┆           ┆        ┆              │
│ NC_083852.1 ┆ Gnomon ┆ exon       ┆ 19483 ┆ … ┆             ┆           ┆        ┆              │
│ NC_083852.1 ┆ Gnomon ┆ exon       ┆ 19336 ┆ … ┆             ┆           ┆        ┆              │
│ …           ┆ …      ┆ …          ┆ …     ┆ … ┆ …           ┆ …         ┆ …      ┆ …            │
│ NC_014295.1 ┆ RefSeq ┆ transcript ┆ 14481 ┆ … ┆             ┆ KEH14_t22 ┆        ┆              │
│ NC_014295.1 ┆ RefSeq ┆ exon       ┆ 14481 ┆ … ┆             ┆ KEH14_t22 ┆        ┆              │
│ NC_014295.1 ┆ RefSeq ┆ gene       ┆ 14548 ┆ … ┆             ┆ KEH14_r01 ┆        ┆              │
│ NC_014295.1 ┆ RefSeq ┆ transcript ┆ 14548 ┆ … ┆             ┆ KEH14_r01 ┆        ┆              │
│ NC_014295.1 ┆ RefSeq ┆ exon       ┆ 14548 ┆ … ┆             ┆ KEH14_r01 ┆        ┆              │
└─────────────┴────────┴────────────┴───────┴───┴─────────────┴───────────┴────────┴──────────────┘

In [10]:
Acer_df = Acer_df.to_pandas()

In [11]:
print((Acer_df["gene_biotype"] != "").sum())
print(Acer_df["gene_id"].nunique())

# print(Acer_df["gene_biotype"].unique())

13145
13145

↑ There is as many rows of non-empty `gene_biotype` as there are `gene_ids`. In other words, in each of the rows corresponding to a `gene_id`, there is one row of non-empty `gene_biotype`.

↓ For a pandas DataFrame, within each `gene_id` group where only one row has a non-empty `gene_biotype` and the rest are empty strings, fill all rows of that group with that single non-empty value.

In [12]:
Acer_df['gene_biotype'] = Acer_df['gene_biotype'].replace('', pd.NA)
#    transform('first') 会跳过 NaN 取第一个有效值，若全为空则返回 NaN: 
Acer_df['gene_biotype'] = Acer_df.groupby('gene_id')['gene_biotype'].transform('first')

In [13]:
print(Acer_df["gene_biotype"].isna().sum())

0

↑ The replacement has been completed.

In [16]:
"gene_biotype" in Acer_df.columns

True

In [ ]:
Acer_df = Acer_df.rename(columns={"seqname": "Chromosome", # 必须重命名, 否则无法转换
                        "start": "Start",
                        "end": "End"})
Acer_df["Start"] = Acer_df["Start"] - 1 # 后续转换成 PyRanges 再写成 GTF 会导致 Start 全体加一, 所以必须在这里预先减一
# new_pr = pr.PyRanges(Acer_df)

In [29]:
Acer_df

,Chromosome,source,feature,Start,End,score,strand,frame,gene_id,db_xref,...,exception,pseudo,transl_except,gene_synonym,partial,deleted,substituted,locus_tag,codons,transl_table
0,NC_083852.1,Gnomon,gene,17568,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,,,,,,,,,,
1,NC_083852.1,Gnomon,transcript,17568,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,,,,,,,,,,
2,NC_083852.1,Gnomon,exon,20092,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,,,,,,,,,,
3,NC_083852.1,Gnomon,exon,19482,19604,NaN,-,0,LOC107992807,GeneID:107992807,...,,,,,,,,,,
4,NC_083852.1,Gnomon,exon,19335,19403,NaN,-,0,LOC107992807,GeneID:107992807,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725100,NC_014295.1,RefSeq,transcript,14480,14547,NaN,-,0,KEH14_t22,,...,,,,,,,,KEH14_t22,,
725101,NC_014295.1,RefSeq,exon,14480,14547,NaN,-,0,KEH14_t22,,...,,,,,,,,KEH14_t22,,
725102,NC_014295.1,RefSeq,gene,14547,15333,NaN,-,0,KEH14_r01,GeneID:64988636,...,,,,,,,,KEH14_r01,,
725103,NC_014295.1,RefSeq,transcript,14547,15333,NaN,-,0,KEH14_r01,,...,,,,,,,,KEH14_r01,,
725104,NC_014295.1,RefSeq,exon,14547,15333,NaN,-,0,KEH14_r01,,...,,,,,,,,KEH14_r01,,

In [34]:
print(f"unique gene_id number: {Acer_df["gene_id"].nunique()}")
print(f"null gene_id number: {(Acer_df["gene_id"] == "").sum()}")
print(f"null transcript_id number: {(Acer_df["transcript_id"] == "").sum()}") # 13145, only null in the gene (not in transcript or exon) line
print(f"null gene_biotype number: {(Acer_df["gene_biotype"] == "").sum()}")
print(f"null transcript_biotype number:{(Acer_df["transcript_biotype"] == "").sum()}")
print(f"null exon_number number: {(Acer_df["exon_number"] == "").sum()}")
print(f"null gene number: {(Acer_df["gene"] == "").sum()}")

# print((Acer_df["pseudo"] == "").sum())

unique gene_id number: 13145
null gene_id number: 0
null transcript_id number: 13145
null gene_biotype number: 0
null transcript_biotype number:352540
null exon_number number: 48348
null gene number: 72

In [35]:
Acer_df = Acer_df.replace("", None)
Acer_df

,Chromosome,source,feature,Start,End,score,strand,frame,gene_id,db_xref,...,exception,pseudo,transl_except,gene_synonym,partial,deleted,substituted,locus_tag,codons,transl_table
0,NC_083852.1,Gnomon,gene,17568,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NC_083852.1,Gnomon,transcript,17568,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NC_083852.1,Gnomon,exon,20092,20211,NaN,-,0,LOC107992807,GeneID:107992807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NC_083852.1,Gnomon,exon,19482,19604,NaN,-,0,LOC107992807,GeneID:107992807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NC_083852.1,Gnomon,exon,19335,19403,NaN,-,0,LOC107992807,GeneID:107992807,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725100,NC_014295.1,RefSeq,transcript,14480,14547,NaN,-,0,KEH14_t22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KEH14_t22,NaN,NaN
725101,NC_014295.1,RefSeq,exon,14480,14547,NaN,-,0,KEH14_t22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KEH14_t22,NaN,NaN
725102,NC_014295.1,RefSeq,gene,14547,15333,NaN,-,0,KEH14_r01,GeneID:64988636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KEH14_r01,NaN,NaN
725103,NC_014295.1,RefSeq,transcript,14547,15333,NaN,-,0,KEH14_r01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KEH14_r01,NaN,NaN
725104,NC_014295.1,RefSeq,exon,14547,15333,NaN,-,0,KEH14_r01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KEH14_r01,NaN,NaN

In [32]:
Acer_df.columns

Index(['Chromosome', 'source', 'feature', 'Start', 'End', 'score', 'strand',
       'frame', 'gene_id', 'db_xref', 'description', 'gbkey', 'gene',
       'gene_biotype', 'transcript_id', 'experiment', 'model_evidence',
       'product', 'transcript_biotype', 'exon_number', 'protein_id', 'part',
       'anticodon', 'inference', 'note', 'exception', 'pseudo',
       'transl_except', 'gene_synonym', 'partial', 'deleted', 'substituted',
       'locus_tag', 'codons', 'transl_table'],
      dtype='str')

In [31]:
Acer_df["transcript_biotype"].unique()

<ArrowStringArray>
['', 'mRNA', 'transcript', 'lnc_RNA', 'tRNA', 'snoRNA', 'snRNA', 'rRNA',
 'ncRNA']
Length: 9, dtype: str

In [25]:
print(Acer_df["Start"].sum())

6152584226511

In [27]:
print(Acer_df["Start"].sum())

6152583501406

In [20]:
print(Acer_df["Start"].sum())
print(Acer_df["End"].sum())

6152584226511
6154108203803

In [22]:
Acer_pr_df = read_gtf("./ref/GCF_029169275.1_AcerK_1.0_genomic_neat.gtf")
Acer_pr_df = Acer_pr_df.to_pandas()
print(Acer_pr_df["start"].sum())
print(Acer_pr_df["end"].sum())

INFO:root:Extracted GTF attributes: ['gene_id', 'db_xref', 'description', 'gbkey', 'gene', 'gene_biotype', 'transcript_id', 'experiment', 'model_evidence', 'product', 'transcript_biotype', 'exon_number', 'protein_id', 'part', 'anticodon', 'inference', 'note', 'exception', 'pseudo', 'transl_except', 'gene_synonym', 'partial', 'deleted', 'substituted', 'locus_tag', 'codons', 'transl_table']

6152584951616
6154108203803

In [24]:
print(6152584951616 - 6152584226511)
print(Acer_df.shape[0])

725105
725105

In [ ]:
new_pr = 
new_pr.to_gtf("./ref/GCF_029169275.1_AcerK_1.0_genomic_neat.gtf")

In [59]:
print(Acer_df["gene_id"].nunique())
print((Acer_df["gene_id"] == "").sum())
print((Acer_df["transcript_id"] == "").sum())
print((Acer_df["gene_biotype"] == "").sum())
print((Acer_df["transcript_biotype"] == "").sum())
print((Acer_df["pseudo"] == "").sum())

13145
0
13145
0
352540
725008

check gene_biotype column using gppy:

In [45]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic_neat.gtf" > "./metadata/Acer_txinfo.tsv"

Traceback (most recent call last):
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/bin/gppy", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 735, in main
    tx_info(args.gtf, args.force_end_check)
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 531, in tx_info
    gtf, tx_meta, metavars= parse_gtf(gtf_file, parse_attrs=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 328, in parse_gtf
    gtf[tx_name].add_region(region = Region(int(ary[3]), int(ary[4])), region_type=ary[2])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "/home/liuzhiyu/Software/miniconda3/envs/Mito_Assemble/lib/python3.12/site-packages/gppy/gtf.py", line 33, in __post_init__
    raise ValueError('Invalid region boundary!')
ValueError: Invalid region boundary!

CalledProcessError: Command 'b'\ngppy txinfo -g "./ref/GCF_029169275.1_AcerK_1.0_genomic_neat.gtf" > "./metadata/Acer_txinfo.tsv"\n'' returned non-zero exit status 1.

In [ ]:
utr5_missing = (Acer_info["utr5_len"] == 0).mean()

print(utr5_missing)

0.20177257620089198

In [36]:
utr3_missing = (Acer_info["utr3_len"] == 0).mean()

print(utr3_missing)

0.17810982018577962

In [37]:
both_missing = ((Acer_info["utr5_len"] == 0) & (Acer_info["utr3_len"] == 0)).mean()

print(both_missing)

0.17518393318751244